name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies for ModelNNFunctionKonfio
      run: |
        cd ModelNNFunctionKonfio
        pip install joblib pandas -t ./

    - name: Install dependencies for KonfioTesting
      run: |
        cd KonfioTesting
        pip install joblib pandas -t ./

    - name: Package Lambda function ModelNNFunctionKonfio
      run: |
        cd ModelNNFunctionKonfio
        zip -r ../ModelNNFunctionKonfio.zip .

    - name: Package Lambda function KonfioTesting
      run: |
        cd KonfioTesting
        zip -r ../KonfioTesting.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update Lambda function ModelNNFunctionKonfio
      run: |
        aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME_001 }} --zip-file fileb://ModelNNFunctionKonfio.zip

    - name: Update Lambda function KonfioTesting
      run: |
        aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME_002 }} --zip-file fileb://KonfioTesting.zip
